version: '3.1'

services:
  redmine:
    image: redmine
    volumes:
      - ../themes/candy:/usr/src/redmine/public/themes/candy
    ports:
      - 80:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine